In [1]:
import numpy as np

In [3]:
np.__version__

'1.21.5'

In [4]:
import pandas as pd

In [5]:
pd.__version__

'1.4.4'

In [6]:
list_1 = [1,2]
list_1

[1, 2]

In [7]:
list_2 = [34,45]
list_2

[34, 45]

In [9]:
list_1.extend(list_2)

In [6]:
import numpy as np

In [7]:
s = 5

In [8]:
s

5

In [9]:
v = np.array([5,-2,4])

In [10]:
v

array([ 5, -2,  4])

In [11]:
m = np.array([[5,12,6],[-3,0,14]])

In [12]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
type(s)

int

In [14]:
type(v)

numpy.ndarray

In [15]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(s)
s_array

array(5)

In [17]:
type(s_array)

numpy.ndarray

In [18]:
m.shape

(2, 3)

In [19]:
v.shape

(3,)

In [20]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [22]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [24]:
s_array.shape

()

In [26]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [28]:
t = np.array([m1,m2])

In [29]:
t.shape

(2, 2, 3)

In [30]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

In [31]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [32]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [33]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [34]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [35]:
v1 + v2

array([6, 6, 6, 6, 6])

In [36]:
v1 - v2

array([-4, -2,  0,  2,  4])

In [39]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [40]:
v1 + 1

array([2, 3, 4, 5, 6])

In [41]:
B  = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [42]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [43]:
C = np.array([[4,-5],[8,12],[-2,3],[19,0]])

In [45]:
C

array([[ 4, -5],
       [ 8, 12],
       [-2,  3],
       [19,  0]])

In [46]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12,  3,  0]])

In [47]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [48]:
np.dot(x,y)

-66

In [50]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [51]:
np.dot(u,v)

18

In [52]:
np.dot(10,-2)

-20

In [53]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])

In [54]:
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [56]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])

In [57]:
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])