In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [5]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.mean(array_b, axis = 0)

array([2.5, 3.5, 4.5])